In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [3]:
train = pd.read_pickle('../datos/procesados/train_EDA.pkl')

In [4]:
train.info()

<class 'pandas.core.frame.DataFrame'>
Index: 28402 entries, 1 to 32580
Data columns (total 12 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   propiedad_vivienda        28402 non-null  object
 1   intencion_prestamo        28402 non-null  object
 2   calificacion_prestamo     28402 non-null  object
 3   incumplimiento_historial  28402 non-null  object
 4   edad                      28402 non-null  int64
 5   ingreso                   28402 non-null  float64
 6   duracion_empleo           28402 non-null  float64
 7   monto_prestamo            28402 non-null  int64
 8   tasa_interes              28402 non-null  float64
 9   estado_prestamo           28402 non-null  int64
 10  porcentaje_ingreso        28402 non-null  float64
 11  duracion_credito          28402 non-null  int64
dtypes: float64(4), int64(4), object(4)
memory usage: 2.8+ MB

# Transformación

## Encoding

Aplicar one hot encoding a las variables categóricas propiedad_vivienda y intencion_prestamo.

In [5]:
cols_ohe = ['propiedad_vivienda', 'intencion_prestamo']

In [6]:
from sklearn.preprocessing import OneHotEncoder

ohe = OneHotEncoder(sparse_output=False, handle_unknown='ignore')
encode = ohe.fit_transform(train[cols_ohe])

# Eliminar originales y unir las codificadas
train = train.drop(columns=cols_ohe)
train = pd.concat([train, pd.DataFrame(encode, columns=ohe.get_feature_names_out(cols_ohe), index=train.index)], axis=1)

Aplicar ordial encoding a la variable categórica calificacion_prestamo.

In [7]:
from sklearn.preprocessing import OrdinalEncoder

categorias = [['G', 'F', 'E', 'D', 'C', 'B', 'A']]

oe = OrdinalEncoder(categories=categorias)
train[["calificacion_prestamo"]] = oe.fit_transform(train[["calificacion_prestamo"]])

In [8]:
train[["calificacion_prestamo"]]

       calificacion_prestamo
1                        5.0
2                        4.0
3                        4.0
4                        4.0
5                        6.0
...                      ...
32576                    4.0
32577                    6.0
32578                    5.0
32579                    5.0
32580                    5.0

[28402 rows x 1 columns]

Aplicar lavel encoding a la variable categórica incumplimiento_historial.

In [9]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
train["incumplimiento_historial"] = le.fit_transform(train["incumplimiento_historial"])

## Reescalado

Reescalado de las variables fuera de rango [0, 1]

In [10]:
from sklearn.preprocessing import MinMaxScaler

cols_escalar = ["edad", "ingreso", "duracion_empleo", "monto_prestamo", 
                "tasa_interes", "duracion_credito", "calificacion_prestamo"]

scaler = MinMaxScaler()

train[cols_escalar] = scaler.fit_transform(train[cols_escalar])

In [11]:
train.describe().T

,count,mean,std,min,25%,50%,75%,max
calificacion_prestamo,28402.0,0.795144,0.195182,0.0,0.666667,0.833333,1.000000,1.00
incumplimiento_historial,28402.0,0.178368,0.382829,0.0,0.000000,0.000000,0.000000,1.00
edad,28402.0,0.120720,0.096504,0.0,0.046875,0.093750,0.156250,1.00
ingreso,28402.0,0.423967,0.089346,0.0,0.367123,0.422793,0.480505,1.00
duracion_empleo,28402.0,0.116700,0.098485,0.0,0.048780,0.097561,0.170732,1.00
monto_prestamo,28402.0,0.265296,0.183427,0.0,0.130435,0.217391,0.347826,1.00
tasa_interes,28402.0,0.315843,0.181578,0.0,0.139326,0.312921,0.452809,1.00
estado_prestamo,28402.0,0.216886,0.412132,0.0,0.000000,0.000000,0.000000,1.00
porcentaje_ingreso,28402.0,0.169455,0.106354,0.0,0.090000,0.150000,0.230000,0.83
duracion_credito,28402.0,0.135775,0.144325,0.0,0.035714,0.071429,0.214286,1.00
propiedad_vivienda_MORTGAGE,28402.0,0.413105,0.492400,0.0,0.000000,0.000000,1.000000,1.00
propiedad_vivienda_OWN,28402.0,0.076544,0.265871,0.0,0.000000,0.000000,0.000000,1.00
propiedad_vivienda_RENT,28402.0,0.510351,0.499902,0.0,0.000000,1.000000,1.000000,1.00
intencion_prestamo_DEBTCONSOLIDATION,28402.0,0.159601,0.366242,0.0,0.000000,0.000000,0.000000,1.00
intencion_prestamo_EDUCATION,28402.0,0.199070,0.399308,0.0,0.000000,0.000000,0.000000,1.00
intencion_prestamo_HOMEIMPROVEMENT,28402.0,0.111823,0.315154,0.0,0.000000,0.000000,0.000000,1.00
intencion_prestamo_MEDICAL,28402.0,0.185022,0.388322,0.0,0.000000,0.000000,0.000000,1.00
intencion_prestamo_PERSONAL,28402.0,0.170446,0.376031,0.0,0.000000,0.000000,0.000000,1.00
intencion_prestamo_VENTURE,28402.0,0.174037,0.379148,0.0,0.000000,0.000000,0.000000,1.00

In [12]:
train.to_pickle('../datos/procesados/train_transformado.pkl')