In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
train = pd.read_pickle('../datos/entrenamiento/train_EDA.pkl')

# Transformación

## Encoding

Aplicar one hot encoding a las variables categóricas propiedad_vivienda y intencion_prestamo.

In [3]:
cols_ohe = ['propiedad_vivienda', 'intencion_prestamo']

In [4]:
from sklearn.preprocessing import OneHotEncoder

ohe = OneHotEncoder(sparse_output=False, handle_unknown='ignore')
encode = ohe.fit_transform(train[cols_ohe])

# Eliminar originales y unir las codificadas
train = train.drop(columns=cols_ohe)
train = pd.concat([train, pd.DataFrame(encode, columns=ohe.get_feature_names_out(cols_ohe), index=train.index)], axis=1)

Aplicar ordial encoding a la variable categórica calificacion_prestamo.

In [5]:
from sklearn.preprocessing import OrdinalEncoder

categorias = [['G', 'F', 'E', 'D', 'C', 'B', 'A']]

oe = OrdinalEncoder(categories=categorias)
train[["calificacion_prestamo"]] = oe.fit_transform(train[["calificacion_prestamo"]])

In [6]:
train[["calificacion_prestamo"]]

       calificacion_prestamo
1                        5.0
2                        4.0
3                        4.0
4                        4.0
5                        6.0
...                      ...
32575                    5.0
32576                    4.0
32577                    6.0
32578                    5.0
32580                    5.0

[27089 rows x 1 columns]

Aplicar lavel encoding a la variable categórica incumplimiento_historial.

In [7]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
train["incumplimiento_historial"] = le.fit_transform(train["incumplimiento_historial"])

## Reescalado

Reescalado de las variables fura de rango [0, 1]

In [8]:
from sklearn.preprocessing import MinMaxScaler

cols_escalar = ["edad", "ingreso", "duracion_empleo", "monto_prestamo", 
                "tasa_interes", "duracion_credito", "calificacion_prestamo"]

scaler = MinMaxScaler()

train[cols_escalar] = scaler.fit_transform(train[cols_escalar])

In [9]:
train.describe().T

,count,mean,std,min,25%,50%,75%,max
edad,27089.0,0.118738,0.095582,0.00,0.046875,0.093750,0.156250,1.00
ingreso,27089.0,0.404707,0.201088,0.00,0.252199,0.366569,0.520528,1.00
duracion_empleo,27089.0,0.114796,0.096651,0.00,0.048780,0.097561,0.170732,1.00
calificacion_prestamo,27089.0,0.795987,0.194518,0.00,0.666667,0.833333,1.000000,1.00
monto_prestamo,27089.0,0.256645,0.175447,0.00,0.130435,0.217391,0.333333,1.00
tasa_interes,27089.0,0.315020,0.181313,0.00,0.139326,0.312921,0.452809,1.00
estado_prestamo,27089.0,0.222563,0.415975,0.00,0.000000,0.000000,0.000000,1.00
porcentaje_ingreso,27089.0,0.173628,0.106629,0.01,0.090000,0.150000,0.230000,0.83
incumplimiento_historial,27089.0,0.177895,0.382431,0.00,0.000000,0.000000,0.000000,1.00
duracion_credito,27089.0,0.133047,0.142592,0.00,0.035714,0.071429,0.214286,1.00
propiedad_vivienda_MORTGAGE,27089.0,0.399756,0.489857,0.00,0.000000,0.000000,1.000000,1.00
propiedad_vivienda_OWN,27089.0,0.076452,0.265724,0.00,0.000000,0.000000,0.000000,1.00
propiedad_vivienda_RENT,27089.0,0.523792,0.499443,0.00,0.000000,1.000000,1.000000,1.00
intencion_prestamo_DEBTCONSOLIDATION,27089.0,0.158847,0.365540,0.00,0.000000,0.000000,0.000000,1.00
intencion_prestamo_EDUCATION,27089.0,0.200672,0.400510,0.00,0.000000,0.000000,0.000000,1.00
intencion_prestamo_HOMEIMPROVEMENT,27089.0,0.109897,0.312767,0.00,0.000000,0.000000,0.000000,1.00
intencion_prestamo_MEDICAL,27089.0,0.186939,0.389870,0.00,0.000000,0.000000,0.000000,1.00
intencion_prestamo_PERSONAL,27089.0,0.169958,0.375603,0.00,0.000000,0.000000,0.000000,1.00
intencion_prestamo_VENTURE,27089.0,0.173687,0.378847,0.00,0.000000,0.000000,0.000000,1.00

In [10]:
train.to_pickle('../datos/entrenamiento/train_transformado.pkl')